### Creates a patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Rabindra Dhant",
  "email": "dhant@gmail.com",
  "address": "88 Elgin Cres",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2025-08-30"
}